// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-dc1wWihNBr-aM_mhTj6kWV2Hylla44o',
    appId: '1:121007224301:web:153919eefca7dff0fd23e4',
    messagingSenderId: '121007224301',
    projectId: 'uber-clone-2031d',
    authDomain: 'uber-clone-2031d.firebaseapp.com',
    storageBucket: 'uber-clone-2031d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9iEqAsHrbMXWDDC150A0axZllVVFudp8',
    appId: '1:121007224301:android:cc8542586c9445e8fd23e4',
    messagingSenderId: '121007224301',
    projectId: 'uber-clone-2031d',
    storageBucket: 'uber-clone-2031d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuGeq-bBBdGnlhGWS5Ba1TQbWKiCbPqH8',
    appId: '1:121007224301:ios:002bf7ae68a51ba0fd23e4',
    messagingSenderId: '121007224301',
    projectId: 'uber-clone-2031d',
    storageBucket: 'uber-clone-2031d.appspot.com',
    iosBundleId: 'com.example.uberCloneApp',
  );
}
